tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autoconf"
brew "autossh"
brew "bat"
brew "cmake"
brew "curl"
brew "go"
brew "dep"
brew "doctl"
brew "erlang"
brew "elixir"
brew "fzf"
brew "git"
brew "libusb"
brew "gnupg"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "libtool"
brew "python"
brew "ruby"
brew "macvim"
brew "man-db"
brew "mas"
brew "nmap"
brew "node"
brew "rust"
brew "nushell"
brew "octant"
brew "pastel"
brew "rclone"
brew "ripgrep"
brew "ship"
brew "starship"
brew "tmux"
brew "watchman"
brew "wget"
brew "wrk"
brew "goreleaser/tap/goreleaser"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "kap"
cask "keybase"
cask "numi"
cask "oracle-jdk"
cask "postman"
cask "runjs"
cask "tableplus"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Dynamo", id: 1445910651
mas "iA Writer", id: 775737590
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Markoff", id: 1084713122
mas "Micro Snitch", id: 972028355
mas "PDF Expert", id: 1055273043
mas "Things", id: 904280696
mas "Xcode", id: 497799835
