tap "github/gh"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "lukakerr/things"
tap "mongodb/brew"
brew "autoconf"
brew "autossh"
brew "bat"
brew "cmake"
brew "curl"
brew "go"
brew "dep"
brew "doctl"
brew "erlang"
brew "elixir"
brew "fzf"
brew "git"
brew "git-delta"
brew "libusb"
brew "gnupg"
brew "hey"
brew "hyperkit"
brew "jq"
brew "kubernetes-cli"
brew "libtool"
brew "python"
brew "ruby"
brew "macvim"
brew "man-db"
brew "mas"
brew "minikube"
brew "neovim"
brew "nmap"
brew "node"
brew "node@12"
brew "nushell"
brew "octant"
brew "pastel"
brew "rclone"
brew "ripgrep"
brew "rust"
brew "ship"
brew "starship"
brew "terraform"
brew "tmux"
brew "watchman"
brew "wget"
brew "wrk"
brew "github/gh/gh"
brew "goreleaser/tap/goreleaser"
brew "mongodb/brew/mongodb-community"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "kap"
cask "keybase"
cask "numi"
cask "oracle-jdk"
cask "pine"
cask "postman"
cask "rq"
cask "runjs"
cask "tableplus"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Acorn", id: 1233861775
mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Dynamo", id: 1445910651
mas "iA Writer", id: 775737590
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Markoff", id: 1084713122
mas "Micro Snitch", id: 972028355
mas "PDF Expert", id: 1055273043
mas "Slack", id: 803453959
mas "Squash", id: 1152443474
mas "Things", id: 904280696
mas "Xcode", id: 497799835
